# TCL File Generated by Component Editor 17.1
# Wed Mar 01 11:58:14 MST 2023
# DO NOT MODIFY


# 
# audio_module "audio_module" v2.0
#  2023.03.01.11:58:14
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module audio_module
# 
set_module_property DESCRIPTION ""
set_module_property NAME audio_module
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "My IP Core"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME audio_module
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL audio_avalon_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file audio_top_level.sv SYSTEM_VERILOG PATH audio_top_level.sv
add_fileset_file divide_by_12.sv SYSTEM_VERILOG PATH divide_by_12.sv
add_fileset_file music_player.sv SYSTEM_VERILOG PATH music_player.sv
add_fileset_file musicrom_v.v VERILOG PATH musicrom_v.v
add_fileset_file audio_avalon_interface.sv SYSTEM_VERILOG PATH audio_avalon_interface.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock_sink_50
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset reset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink_50
set_interface_property conduit_end associatedReset clock_reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end speaker writeresponsevalid_n Output 1


# 
# connection point clock_sink_25
# 
add_interface clock_sink_25 clock end
set_interface_property clock_sink_25 clockRate 0
set_interface_property clock_sink_25 ENABLED true
set_interface_property clock_sink_25 EXPORT_OF ""
set_interface_property clock_sink_25 PORT_NAME_MAP ""
set_interface_property clock_sink_25 CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink_25 SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_25 clock25 clk Input 1


# 
# connection point clock_sink_50
# 
add_interface clock_sink_50 clock end
set_interface_property clock_sink_50 clockRate 0
set_interface_property clock_sink_50 ENABLED true
set_interface_property clock_sink_50 EXPORT_OF ""
set_interface_property clock_sink_50 PORT_NAME_MAP ""
set_interface_property clock_sink_50 CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink_50 SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_50 clock50 clk Input 1


# 
# connection point avalon_slave_0_1
# 
add_interface avalon_slave_0_1 avalon end
set_interface_property avalon_slave_0_1 addressUnits WORDS
set_interface_property avalon_slave_0_1 associatedClock clock_sink_50
set_interface_property avalon_slave_0_1 associatedReset clock_reset
set_interface_property avalon_slave_0_1 bitsPerSymbol 8
set_interface_property avalon_slave_0_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0_1 burstcountUnits WORDS
set_interface_property avalon_slave_0_1 explicitAddressSpan 0
set_interface_property avalon_slave_0_1 holdTime 0
set_interface_property avalon_slave_0_1 linewrapBursts false
set_interface_property avalon_slave_0_1 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0_1 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0_1 readLatency 0
set_interface_property avalon_slave_0_1 readWaitTime 1
set_interface_property avalon_slave_0_1 setupTime 0
set_interface_property avalon_slave_0_1 timingUnits Cycles
set_interface_property avalon_slave_0_1 writeWaitTime 0
set_interface_property avalon_slave_0_1 ENABLED true
set_interface_property avalon_slave_0_1 EXPORT_OF ""
set_interface_property avalon_slave_0_1 PORT_NAME_MAP ""
set_interface_property avalon_slave_0_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0_1 writedata writedata Input 32
add_interface_port avalon_slave_0_1 write write Input 1
add_interface_port avalon_slave_0_1 read read Input 1
add_interface_port avalon_slave_0_1 readdata readdata Output 32
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0_1 embeddedsw.configuration.isPrintableDevice 0

