# TCL File Generated by Component Editor 17.1
# Mon Apr 03 12:15:57 MDT 2023
# DO NOT MODIFY


# 
# sine_wave_audio_module "sine_wave_ audio_module" v1.0
#  2023.04.03.12:15:57
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module sine_wave_audio_module
# 
set_module_property DESCRIPTION ""
set_module_property NAME sine_wave_audio_module
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "My IP Core"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "sine_wave_ audio_module"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL audio_avalon_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file audio_avalon_interface.sv SYSTEM_VERILOG PATH audio_avalon_interface.sv TOP_LEVEL_FILE
add_fileset_file counter.sv SYSTEM_VERILOG PATH counter.sv
add_fileset_file downcounter.sv SYSTEM_VERILOG PATH downcounter.sv
add_fileset_file sine_wave.sv SYSTEM_VERILOG PATH sine_wave.sv
add_fileset_file sine_wave_audio_top_level.sv SYSTEM_VERILOG PATH sine_wave_audio_top_level.sv
add_fileset_file sine_wave_song.sv SYSTEM_VERILOG PATH sine_wave_song.sv
add_fileset_file posedge_det.sv SYSTEM_VERILOG PATH posedge_det.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink_50
set_interface_property avalon_slave_0 associatedReset clock_reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 write write Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink_50
set_interface_property conduit_end associatedReset clock_reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end speaker readdata Output 7


# 
# connection point clock_sink_25
# 
add_interface clock_sink_25 clock end
set_interface_property clock_sink_25 clockRate 0
set_interface_property clock_sink_25 ENABLED true
set_interface_property clock_sink_25 EXPORT_OF ""
set_interface_property clock_sink_25 PORT_NAME_MAP ""
set_interface_property clock_sink_25 CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink_25 SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_25 clock25 clk Input 1


# 
# connection point clock_sink_50
# 
add_interface clock_sink_50 clock end
set_interface_property clock_sink_50 clockRate 0
set_interface_property clock_sink_50 ENABLED true
set_interface_property clock_sink_50 EXPORT_OF ""
set_interface_property clock_sink_50 PORT_NAME_MAP ""
set_interface_property clock_sink_50 CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink_50 SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_50 clock50 clk Input 1


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock_sink_50
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset reset_n reset_n Input 1

